listen = "0.0.0.0:3001"
client_urls = ["http://localhost:5173"]
db_uri = "host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Europe/Rome"
auth_uri = "http://localhost:3000"
